#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      # Persönlicher vorname1 Key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC36qk7SFqP6U/sFvr2ARq29xv3q9MI01mFrlIDN05snykJzWJZz616sCyhNkE+h9uT4GH6YVPhi3bxFBWfEtfKY3Lztf2/hYL4Y4aqByQZ6cb28WQjijjw2xN1yhunQM5Y+U4S7mV2leZ7xLFfWwXoQdJfbUT3A6XN2DAMHH7PgoLA68WxOy1fIDEPs9kfM/KUCdm/jyGM7RxzKw9xrs9gsFmtb7ZKKWPGYJ0de/L9vRoFC1wGsSBjNVTto/HG/Zn5a+5jdUVvO5MdfWikq8Ky2hOPUQQ36HC9CCpDyuSzdcYiOVFccmzA4HibTjgI0oh09Z0BKtCis+2uDZQBL0Z/ aws-key
      # Lehrer Key
      - ssh-rsa MIIBCgKCAQEA8lshkw886qvWI7jKrK3F0TIWVawmw/nJy9mC6Uy205Yto13F+piEllc6z0FhJBeTj1glbVqVKchII8Hu5uxOc76SNGxoj63c6z5juUjIRSNIESSuVXSRFZefVwqJW+Lnqod3ML6W19pDFfH6tOFmPkqPJhhZWfhAfknb1pIHc3XtCjqF/KWUI3v6w+hqRxfSY7pdO+Q9ZJpUuGlJVJhpDN3OmeY/6YS48k0Wsijg/3WckxFUhmWkvXLHd0Lv2/fKqB/Vabxu/q4vkTTIdyGJCKTkSY4ZQscb2+rk0fPVnLzU/eJDQQNBlBAkJILhJS48fVkkdEcIpnzr+G/hMI/7FwIDAQAB aws-key
ssh_pwauth: false
disable_root: false
package_update: true
packages:
  - curl
  - wget

runcmd:
  # Installiere MariaDB
  - sudo apt-get update
  - sudo apt-get install -y mariadb-server
  # Ändere die Konfiguration, um externe Verbindungen zu erlauben
  - sudo sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf
  # Starte MariaDB neu
  - sudo systemctl restart mariadb
  # Zeige den relevanten Schlüssel der Konfigurationsdatei an
  - sudo grep 'bind-address' /etc/mysql/mariadb.conf.d/50-server.cnf
  # Zeige Status von MariaDB an
  - sudo systemctl status mariadb
